esphome:
  name: esp32-fan

esp32:
  board: esp32-c3-devkitm-1
  framework: { type: esp-idf }

logger:
  baud_rate: 115200

wifi:
  ssid: "Bbox_IoT2"
  password: "bbox_iot"
  fast_connect: true
  ap:
    ssid: "ESP32"
    password: "12345678"

# Pour configurer le Wi-Fi depuis un téléphone/PC
improv_serial:
captive_portal:

api:
ota:
